package views;

import controllers.ThongKePanelController;
import javax.swing.JFrame;

/**
 *
 * @author ai làm thì điền tên vô
 */
public class ThongKePanel extends javax.swing.JPanel {

    private JFrame parentFrame;
    private ThongKePanelController controller;

    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.controller = new ThongKePanelController(tuNgayJdc, denNgayJdc, tinhTrangDichTeJcb, tableJpn);
        this.controller.setDataTable(0);
        timeJpn.setVisible(false);
        tinhTrangDichTeJpn.setVisible(false);
        danhSachDaKhaiBaoControlJpn.setVisible(false);
        soNguoiKhaiBaoJtf.setText(controller.setSoNguoiKhaiBao());
        soNguoiKhaiBaoJtf.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderChoose = new javax.swing.ButtonGroup();
        statusChoose = new javax.swing.ButtonGroup();
        tableJpn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        danhSachDaKhaiBaoControlJpn = new javax.swing.JPanel();
        timeJpn = new javax.swing.JPanel();
        tuNgayJdc = new com.toedter.calendar.JDateChooser();
        denNgayJdc = new com.toedter.calendar.JDateChooser();
        tuJlb = new javax.swing.JLabel();
        denJlb = new javax.swing.JLabel();
        tinhTrangDichTeJpn = new javax.swing.JPanel();
        tinhTrangDichTeJlb = new javax.swing.JLabel();
        tinhTrangDichTeJcb = new javax.swing.JComboBox<>();
        locBtn = new javax.swing.JButton();
        danhSachDaKhaiBaoJpn = new javax.swing.JPanel();
        danhSachDaKhaiBaobtn = new javax.swing.JButton();
        soNguoiKhaiBaoJlb = new javax.swing.JLabel();
        soNguoiKhaiBaoJtf = new javax.swing.JTextField();
        soNguoiKhaiBaoJlb1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(803, 501));

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("DANH SÁCH CÔNG DÂN CHƯA KHAI BÁO Y TẾ");

        timeJpn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timeJpnPropertyChange(evt);
            }
        });

        tuNgayJdc.setDate(new java.util.Date(1546323085000L));
        tuNgayJdc.setEnabled(false);

        denNgayJdc.setEnabled(false);

        tuJlb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tuJlb.setText("Từ:");

        denJlb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        denJlb.setText("Đến:");

        javax.swing.GroupLayout timeJpnLayout = new javax.swing.GroupLayout(timeJpn);
        timeJpn.setLayout(timeJpnLayout);
        timeJpnLayout.setHorizontalGroup(
            timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeJpnLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tuJlb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denJlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(denNgayJdc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuNgayJdc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timeJpnLayout.setVerticalGroup(
            timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeJpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tuJlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tuNgayJdc, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(timeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(denNgayJdc, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(denJlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tinhTrangDichTeJlb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tinhTrangDichTeJlb.setText("Tình trạng dịch tễ:");

        tinhTrangDichTeJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tinhTrangDichTeJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toan Bo", "NULL", "F0", "F1", "F2" }));

        locBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        locBtn.setText("LỌC");
        locBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tinhTrangDichTeJpnLayout = new javax.swing.GroupLayout(tinhTrangDichTeJpn);
        tinhTrangDichTeJpn.setLayout(tinhTrangDichTeJpnLayout);
        tinhTrangDichTeJpnLayout.setHorizontalGroup(
            tinhTrangDichTeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tinhTrangDichTeJpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tinhTrangDichTeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(locBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinhTrangDichTeJlb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tinhTrangDichTeJcb, 0, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        tinhTrangDichTeJpnLayout.setVerticalGroup(
            tinhTrangDichTeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tinhTrangDichTeJpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tinhTrangDichTeJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinhTrangDichTeJlb)
                    .addComponent(tinhTrangDichTeJcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(locBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout danhSachDaKhaiBaoControlJpnLayout = new javax.swing.GroupLayout(danhSachDaKhaiBaoControlJpn);
        danhSachDaKhaiBaoControlJpn.setLayout(danhSachDaKhaiBaoControlJpnLayout);
        danhSachDaKhaiBaoControlJpnLayout.setHorizontalGroup(
            danhSachDaKhaiBaoControlJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhSachDaKhaiBaoControlJpnLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(timeJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(tinhTrangDichTeJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        danhSachDaKhaiBaoControlJpnLayout.setVerticalGroup(
            danhSachDaKhaiBaoControlJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhSachDaKhaiBaoControlJpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(danhSachDaKhaiBaoControlJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinhTrangDichTeJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        danhSachDaKhaiBaobtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        danhSachDaKhaiBaobtn.setText("XEM");
        danhSachDaKhaiBaobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhSachDaKhaiBaobtnActionPerformed(evt);
            }
        });

        soNguoiKhaiBaoJlb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        soNguoiKhaiBaoJlb.setForeground(new java.awt.Color(204, 0, 51));
        soNguoiKhaiBaoJlb.setText("Danh sách người dân đã khai báo y tế:");

        soNguoiKhaiBaoJtf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soNguoiKhaiBaoJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soNguoiKhaiBaoJtfActionPerformed(evt);
            }
        });

        soNguoiKhaiBaoJlb1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        soNguoiKhaiBaoJlb1.setForeground(new java.awt.Color(204, 0, 51));
        soNguoiKhaiBaoJlb1.setText("Số người đã khai báo y tế:");

        javax.swing.GroupLayout danhSachDaKhaiBaoJpnLayout = new javax.swing.GroupLayout(danhSachDaKhaiBaoJpn);
        danhSachDaKhaiBaoJpn.setLayout(danhSachDaKhaiBaoJpnLayout);
        danhSachDaKhaiBaoJpnLayout.setHorizontalGroup(
            danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhSachDaKhaiBaoJpnLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soNguoiKhaiBaoJlb)
                    .addComponent(soNguoiKhaiBaoJlb1))
                .addGap(82, 82, 82)
                .addGroup(danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soNguoiKhaiBaoJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(danhSachDaKhaiBaobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        danhSachDaKhaiBaoJpnLayout.setVerticalGroup(
            danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, danhSachDaKhaiBaoJpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soNguoiKhaiBaoJtf, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(soNguoiKhaiBaoJlb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(danhSachDaKhaiBaoJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(danhSachDaKhaiBaobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soNguoiKhaiBaoJlb))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(danhSachDaKhaiBaoJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(danhSachDaKhaiBaoControlJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(danhSachDaKhaiBaoJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(danhSachDaKhaiBaoControlJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locBtnActionPerformed
        // TODO add your handling code here:
        controller.setData(1);
    }//GEN-LAST:event_locBtnActionPerformed

    private void soNguoiKhaiBaoJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soNguoiKhaiBaoJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soNguoiKhaiBaoJtfActionPerformed

    private void danhSachDaKhaiBaobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhSachDaKhaiBaobtnActionPerformed
        // TODO add your handling code here:
        timeJpn.setVisible(true);
        tinhTrangDichTeJpn.setVisible(true);
        danhSachDaKhaiBaoJpn.setVisible(false);
        danhSachDaKhaiBaoControlJpn.setVisible(true);
        controller.setData(1);
        jLabel1.setVisible(false);
    }//GEN-LAST:event_danhSachDaKhaiBaobtnActionPerformed

    private void timeJpnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_timeJpnPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_timeJpnPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderChoose;
    private javax.swing.JPanel danhSachDaKhaiBaoControlJpn;
    private javax.swing.JPanel danhSachDaKhaiBaoJpn;
    private javax.swing.JButton danhSachDaKhaiBaobtn;
    private javax.swing.JLabel denJlb;
    private com.toedter.calendar.JDateChooser denNgayJdc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton locBtn;
    private javax.swing.JLabel soNguoiKhaiBaoJlb;
    private javax.swing.JLabel soNguoiKhaiBaoJlb1;
    private javax.swing.JTextField soNguoiKhaiBaoJtf;
    private javax.swing.ButtonGroup statusChoose;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JPanel timeJpn;
    private javax.swing.JComboBox<String> tinhTrangDichTeJcb;
    private javax.swing.JLabel tinhTrangDichTeJlb;
    private javax.swing.JPanel tinhTrangDichTeJpn;
    private javax.swing.JLabel tuJlb;
    private com.toedter.calendar.JDateChooser tuNgayJdc;
    // End of variables declaration//GEN-END:variables
}
